# Generated by Django 5.0.3 on 2024-03-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_complated',
            new_name='is_completed',
        ),
    ]
